kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: quay.vapo.va.gov/marcos.serranojr/helm_demo:v1.3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always          
      imagePullSecrets:
      - name: {{ .Values.secret }}
