kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name:  {{ .Values.appname }}-route
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  to:
    kind: Service
    name: {{ .Values.appname }}
