kind: Route
 apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: {{ .Values.appname }}
      name: {{ .Values.appname }}-route
    spec:
      to:
        kind: Service
        name: {{ .Values.appname }}
