kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080  
