kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-hello-helm  
  namespace: {{ .Values.namespace }}
  labels:
    app: php-hello-helm
    app.kubernetes.io/part-of: php-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-hello-helm
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php-hello-helm
    spec:
      containers:
        - name: php-hello-helm
          image: 'quay.vapo.va.gov/marcos.serranojr/helm_demo:v1.3'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always          
      imagePullSecrets:
      - name: robot-account
